# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.CharField(max_length=10)),
                ('ID', models.CharField(max_length=6)),
                ('Prereqs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('Title', models.CharField(max_length=1000)),
                ('Instructors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), size=None)),
                ('Location', models.CharField(max_length=1000)),
                ('Credits', models.IntegerField()),
                ('Level', models.CharField(max_length=1000)),
            ],
        ),
    ]
