# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 22:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Credits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='course',
            name='Instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=1000, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='Prereqs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=10, null=True), blank=True, null=True, size=None),
        ),
    ]
