# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160605_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Credits',
            new_name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Instructors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Prereqs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Title',
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(related_name='_course_prerequisites_+', to='app.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='ID',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='transcript',
            name='courses',
            field=models.ManyToManyField(to='app.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(to='app.Instructor'),
        ),
    ]
