# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 18:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160608_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterTranscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=[], size=None),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
        migrations.AddField(
            model_name='semestertranscript',
            name='courses',
            field=models.ManyToManyField(to='app.Course'),
        ),
        migrations.AddField(
            model_name='completetranscript',
            name='semesters',
            field=models.ManyToManyField(to='app.SemesterTranscript'),
        ),
    ]
